### PR TITLE
fixed error in atachement of disaster alert

### PR DESCRIPTION
**Pull request by minedcp**
added suod() in function _render_qweb_pdf.

### CODE REVIEW

**Comment by ecino** [comment]
What was the access error message ? We might miss a security access instead.

**Comment by minedcp** [comment]
image
this was the message error

**Comment by minedcp** [comment]
image
here is the error message.

**Comment by minedcp** [comment]
corrected the code by removing the sudo

**Review by ecino — APPROVED** [review]

**Pull request merged**
