### PR TITLE
Fix Number of Sponsorships

### PR DESCRIPTION
**Pull request by maxime-beck**

### CODE REVIEW

**Review by davidwul — CHANGES_REQUESTED** [review]
Actually, it's the opposite. sponsorship active = state active and sponsorship_disbursed is state=active and hold_cdsp_funds = false (hold means don't disbursed)

**Comment by ecino** [comment]
As it is now, I don't see any difference in the result, just another way of having the same list.

**Comment by maxime-beck** [comment]
@ecino The difference resides in the fact that apparently, the hold_cdsp_funds of ICPs may be null when it does not contains life cycles[1]. Because of this, the first solution's results were wrong.

To prevent that, maybe we could set the default value of all the booleans life cycles relational fields to false?

---
[1] https://github.com/CompassionCH/compassion-modules/blob/10.0/child_compassion/models/project_compassion.py#L280

**Review by ecino — APPROVED** [review]
In that case I think your change is good, we don't need to set default values. @davidwul you can merge if ok for you.

**Review by davidwul — APPROVED** [review]

**Pull request merged**
