### PR TITLE
14 T1236 

### PR DESCRIPTION
**Pull request by langjer**
Additional payment reference in the customer's language. To be fully functional, some terms need to be translated.

### CODE REVIEW

**Comment by davidwul** [comment]
Very good, 
Some suggestions:
1. the period is the same for all lines, I propose to put it once at the end.
2. you need to use prefered_name for the child name instead of name
3. if the gift wizzard is used and a comment is set, this should be the ref.
4. to find if it's a child gift product, use the product category (categ_id) **Sponsor gifts**. There are some gift invoice generated from contracts
5. if a product is use to "round up" the amount this should not be mentioned as a fund (product), it might be stated it's Sponsorship **Plus** instead of a Sponsorship

**Comment by langjer** [comment]
> * the period is the same for all lines, I propose to put it once at the end.
> 
> * you need to use prefered_name for the child name instead of name
> 
> * if the gift wizzard is used and a comment is set, this should be the ref.
> 
> * to find if it's a child gift product, use the product category (categ_id) **Sponsor gifts**. There are some gift invoice generated from contracts
> 
> * if a product is use to "round up" the amount this should not be mentioned as a fund (product), it might be stated it's Sponsorship **Plus** instead of a Sponsorship

[T1236: Logic changes and corrections](https://github.com/CompassionCH/compassion-switzerland/pull/1593/commits/7e59a98ad3f21f2bfc9322daebd2dedbecb961eb)

1. Check if the date is the same for all lines, if is, the date is displayed at the end, however, the date is displayed after each product in brackets
2. Preferred child name is now used for gifts
3. The gift **description** default is set on the _"display_name"_ of the target product, the **description** is now _compared with it_. **If** there are **identical**, computing a better description like **"{Product name} for {Prefered child's name}."**. Then, **if** there is a _custom description_ (called _additional comment_ in the wizard), a compute is done **like the first one**, but **followed by "Additional comment: [comment]"**. This is **applied only if a gift wizard is detected**.
4. The category id is now used to verify if the product is a gift.
5. If the subtotal of a contract line **is lesser than 20%** of the **total contract line amount**, she's **ignored and not included** in the _readable reference_.

Others changes:
- Re-basing the logic of the contract lines instead of invoices lines, more data's transmitted in.
- Optimizing as much as possible the script
- Some others little fixes

**Review by ecino — DISMISSED** [review]
Code looks good for me, @davidwul please verify as well. You can merge if it's ok for you.

**Comment by langjer** [comment]
[T1236: Logic adaptations and corrections](https://github.com/CompassionCH/compassion-switzerland/pull/1593/commits/2816b53e6a573dec97557836ff4b35bfa803de9b)
- Pluralization of product's name (related to the **following SQL request**, had to be executed after module update).
- Optimization of some method parts.
- `is_unique_period` became `get_unique_occurrence` (work differently, more powerful).
- `get_unique_occurrence` now used for child in the customer readable payment reference display, if is multiple products for a unique child, display the child's name.
-  Added method documentations.

**SQL to execute after merge and update to ensure a correct functioning:**
```
-- Update if existing rows match the condition
UPDATE ir_translation
SET "value" = CASE
                WHEN "lang" = 'de_DE' AND "src" = 'Sponsorships' AND "name" = 'product.template,plural_name' AND "module" = 'sponsorship_switzerland' AND "state" = 'to_translate'
    			THEN 'Patenschaften'            
				WHEN "lang" = 'fr_CH' AND "src" = 'Sponsorships' AND "name" = 'product.template,plural_name' AND "module" = 'sponsorship_switzerland' AND "state" = 'to_translate'
                THEN 'Parrainages'
                WHEN "lang" = 'it_IT' AND "src" = 'Sponsorships' AND "name" = 'product.template,plural_name' AND "module" = 'sponsorship_switzerland' AND "state" = 'to_translate'
                THEN 'Sponsorizzazioni'
                ELSE "value" -- Keep the existing value if no update occurs
              END,
    "state" = 'translated' -- Update the state to 'translated'
WHERE
    "lang" IN ('de_DE', 'fr_CH', 'it_IT') AND
    "src" = 'Sponsorships' AND
    "name" = 'product.template,plural_name' AND
    "res_id" = 2 AND
    "module" = 'sponsorship_switzerland' AND
    "state" = 'to_translate' AND -- Update only if the state is 'to_translate'
    "type" = 'model';

-- Insert new rows where update didn't affect any existing rows
INSERT INTO ir_translation ("lang", "src", "name", "res_id", "module", "state", "value", "type", "comments")
SELECT *
FROM (VALUES
    ('de_DE', 'Sponsorships', 'product.template,plural_name', 2, 'sponsorship_switzerland', 'translated', 'Patenschaften', 'model', ''),
    ('fr_CH', 'Sponsorships', 'product.template,plural_name', 2, 'sponsorship_switzerland', 'translated', 'Parrainages', 'model', ''),
    ('it_IT', 'Sponsorships', 'product.template,plural_name', 2, 'sponsorship_switzerland', 'translated', 'Sponsorizzazioni', 'model', '')
) AS new_rows ("lang", "src", "name", "res_id", "module", "state", "value", "type", "comments")
WHERE NOT EXISTS (
    SELECT 1
    FROM ir_translation AS existing
    WHERE
        existing."lang" = new_rows."lang" AND
        existing."src" = new_rows."src" AND
        existing."name" = new_rows."name" AND
        existing."res_id" = new_rows."res_id" AND
        existing."module" = new_rows."module" AND
        existing."state" = new_rows."state" AND
        existing."type" = new_rows."type"
);
```

**Comment by ecino** [comment]
@langjer Please add a migration script with your SQL query. @davidwul Do you think it's good to add a plural field for the product names that will be used for "Parrainage"/"Parrainages" ? The code is quite flexible with this but let me know your opinion.

**Comment by langjer** [comment]
[T1236: Fix child name call. Migration script to add "Sponsorship" translation added](https://github.com/CompassionCH/compassion-switzerland/pull/1593/commits/e86d20066fd17da8289b42ecabe2a7880e2fd5d9)

- Fixed incorrect child name variable call (forgotten on last commit).
- Add migration script to add plural translation of sponsorships (makes it unnecessary to run SQL).

**Comment by ecino** [comment]
Thanks! Manually merged to fix the conflicts and also replaced the migration script with proper translation files.

**Pull request closed without merging**
